### ISSUE TITLE
Artifact resolution problem

### ISSUE THREAD

**Issue by omainegra** [softwaremill/sttp#1]
I can't manage to get it working with other handlers like `Monix` or `Future`, because of a resolution problem with dependency `async-http-client-handler`. 

Tested in version *0.0.2*

**Comment by adamw** [comment]
What kind of errors do you see? And where? Did you add the required dependency to sbt?

**Comment by omainegra** [comment]
Yes, I did. These are my dependencies:

```scala
libraryDependencies ++= Seq (
  "com.softwaremill.sttp" %% "core" % "0.0.2",
  "com.softwaremill.sttp" %% "async-http-client-handler-future" % "0.0.2",
  "com.softwaremill.sttp" %% "async-http-client-handler-monix" % "0.0.2",

  "org.scalatest" %% "scalatest" % "3.0.1" % Test
)
```

And this is the log:

```scala
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.softwaremill.sttp#async-http-client-handler_2.12;0.0.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.softwaremill.sttp:async-http-client-handler_2.12:0.0.2
[warn] 		  +- com.softwaremill.sttp:async-http-client-handler-future_2.12:0.0.2 (/Users/omainegra/Repositories/hello-scala-sttp/build.sbt#L6-13)
[warn] 		  +- com.example:hello_2.12:0.1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.softwaremill.sttp#async-http-client-handler_2.12;0.0.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
```

**Comment by omainegra** [comment]
But it seems to be a problem with the artifact `async-http-client-handler`, which is not published to maven central.

<img width="1214" alt="screen shot 2017-07-26 at 10 51 40 am" src="https://user-images.githubusercontent.com/7846263/28627900-135d249c-71f1-11e7-821a-d0bd27ebbc62.png">

**Comment by adamw** [comment]
Indeed, let me see ...

**Comment by adamw** [comment]
I'm releasing the missing artifact now, should be in central in ~15 minutes

**Comment by omainegra** [comment]
Thanks, BTW **sttp** is really amazing. +1 For **Monix** integration

**Comment by adamw** [comment]
Thanks, hopefully it will live up to that opinion once you'll be able to resolve the dependencies ;)

**Comment by omainegra** [comment]
Done. The artifact is published.
