### ISSUE TITLE
java.lang.IllegalArgumentException: : could not be parsed into a proper Uri, missing scheme

### ISSUE THREAD

**Issue by key-eugene** [softwaremill/sttp#1072]
I recently encountered a weird bug. My service accepts some URLs from users and makes requests to those. 
What I'm doing: 
```
val parsedString = sttp.model.Uri.parse(string).toOption.get
val responsF = sttpBackend.send(basicRequest.get(parsedString).response(asByteArray))
```
And it worked fine until provided `string` became `""` (empty string) then it failed with:
```
java.lang.IllegalArgumentException: : could not be parsed into a proper Uri, missing scheme
	at org.asynchttpclient.uri.Uri.create(Uri.java:70)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147)
	at sttp.client3.asynchttpclient.AsyncHttpClientBackend.requestToAsync(AsyncHttpClientBackend.scala:196)
	at sttp.client3.asynchttpclient.AsyncHttpClientBackend.$anonfun$preparedRequest$2(AsyncHttpClientBackend.scala:190)
	at scala.util.Try$.apply(Try.scala:210)
```
Is it expected behavior? I thought if `sttp.model.Uri.parse` was successful then it was supposed to execute the request or am I missing something? 

(reproducible example)
```
val parsedUrl = sttp.model.Uri.parse("").toOption.get
val str = parsedUrl.toString() // returns `:`
val uri = org.asynchttpclient.uri.Uri.create(str) // boom
```

**Comment by adamw** [comment]
Hm indeed that's weird, but some hint as to why this happens might be that sttp's `Uri` represents both relative and absolute uris, and probably `""` gets parsed into a relative uri somehow. Not sure why there's a `:` (the port separator) in there then. So maybe that's not it :)
