### ISSUE TITLE
URI.resolve can throw exception

### ISSUE THREAD

**Issue by somdoron** [softwaremill/sttp#1170]
We are using the library for dispatching webhook events, one of the endpoints returned a redirect response with an invalid location (location with spaces) which throw an exception and crashed the app. We are using version `3.3.15` with `httpclient-backend-zio`, stack trace below:

```
java.lang.IllegalArgumentException: Illegal character in path at index 2: go away !!! (/)
? 	at java.base/java.net.URI.create(URI.java:883)
? 	at java.base/java.net.URI.resolve(URI.java:1066)
? 	at sttp.client3.FollowRedirectsBackend.followRedirect(FollowRedirectsBackend.scala:61)
? 	at sttp.client3.FollowRedirectsBackend.$anonfun$followRedirect$2(FollowRedirectsBackend.scala:48)
? 	at scala.Option.fold(Option.scala:263)
? 	at sttp.client3.FollowRedirectsBackend.followRedirect(FollowRedirectsBackend.scala:44)
? 	at sttp.client3.FollowRedirectsBackend.$anonfun$sendWithCounter$1(FollowRedirectsBackend.scala:29)
? 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:914)
? 	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
? 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
? 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
? 	at java.base/java.lang.Thread.run(Thread.java:834)
? Caused by: java.net.URISyntaxException: Illegal character in path at index 2: go away !!! (/)
? 	at java.base/java.net.URI$Parser.fail(URI.java:2913)
? 	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
? 	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
? 	at java.base/java.net.URI$Parser.parse(URI.java:3125)
? 	at java.base/java.net.URI.<init>(URI.java:600)
? 	at java.base/java.net.URI.create(URI.java:881)
```

I think the call to resolve should be inside a try expression or the location has first to be validated.

**Comment by adamw** [comment]
Can you provide an example to reproduce the problem? Maybe resolve should return a `Try`, or maybe we should improve `resolve` itself :)

**Comment by somdoron** [comment]
yes, try the following:


```
import sttp.client3._
import sttp.client3.httpclient.zio.HttpClientZioBackend

object MyApp extends zio.App {
  override def run(args: List[String]) = {
    val request = basicRequest
      .post(uri"https://in.gr")
      .body("""{"a": "b"}""")
      .contentType("application/json")

    HttpClientZioBackend.managed().use(_.send(request))
  }
}
```

**Comment by adamw** [comment]
Even if we validate the location, I think the only thing that we can do is return a failed effect (which is done above). Or do you have some other ideas?

**Comment by somdoron** [comment]
I agree, the problem is that at a moment it doesn't return a failed effect but failed with an exception that the ZIO backend doesn't handle. There is no way to catch it because it is thrown within the ZIO loop.

**Comment by adamw** [comment]
See: https://github.com/softwaremill/sttp/pull/1185, should fix the problem

**Comment by somdoron** [comment]
Thank you
