### ISSUE TITLE
AkkaHttpBackend Error

### ISSUE THREAD

**Issue by jiangnight** [softwaremill/sttp#134]
Hello,when i run your AkkaHttpBackend demo,some Error comes!

Information:2018/7/27 16:09 - Compilation completed with 3 errors and 0 warnings in 3s 222ms
Error:scalac: Error: head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at scala.collection.immutable.Nil$.head(List.scala:425)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBoundsErrorMessage(ContextErrors.scala:1052)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBounds(ContextErrors.scala:1059)
	at scala.tools.nsc.typechecker.Infer$Inferencer.issueBoundsError$1(Infer.scala:881)
	at scala.tools.nsc.typechecker.Infer$Inferencer.check$1(Infer.scala:887)
	at scala.tools.nsc.typechecker.Infer$Inferencer.checkBounds(Infer.scala:891)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkBounds(RefChecks.scala:1208)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkTypeRef(RefChecks.scala:1389)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transform$4(RefChecks.scala:1725)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transform$4$adapted(RefChecks.scala:1716)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$Lambda$811/1053548150.apply(Unknown Source)
	at scala.reflect.internal.tpe.TypeMaps$ForEachTypeTraverser.traverse(TypeMaps.scala:1102)
	at scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:297)
	at scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:295)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
	at scala.reflect.internal.tpe.TypeMaps$ForEachTypeTraverser.traverse(TypeMaps.scala:1103)
	at scala.reflect.internal.Types$Type.foreach(Types.scala:787)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1412)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
	at scala.reflect.internal.Trees.$anonfun$itransform$1(Trees.scala:1378)
	at scala.reflect.internal.Trees$$Lambda$377/880507990.apply(Unknown Source)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1377)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1191)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1387)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
	at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1384)
	at scala.reflect.internal.Trees$$Lambda$376/802454436.apply(Unknown Source)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1382)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1203)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1425)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
	at scala.reflect.internal.Trees.$anonfun$itransform$5(Trees.scala:1434)
	at scala.reflect.internal.Trees$$Lambda$667/1459832001.apply(Unknown Source)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1433)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1203)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1174)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
	at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1447)
	at scala.reflect.internal.Trees$$Lambda$666/187118434.apply(Unknown Source)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1447)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
	at scala.tools.nsc.Global$GlobalPhase$$Lambda$333/859912933.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:131)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:32)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:68)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:25)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
/Users/jiang/ScalaPro/sttpScala/src/main/scala/com/sttp/test/HelloSttp.scala
    Error:Error:line (20)Symbol 'type akka.stream.scaladsl.Source' is missing from the classpath.
This symbol is required by 'class com.softwaremill.sttp.akkahttp.AkkaHttpBackend'.
Make sure that type Source is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'AkkaHttpBackend.class' was compiled against an incompatible version of akka.stream.scaladsl.
    implicit val backend = AkkaHttpBackend()
    Error:Error:line (20)type arguments [scala.concurrent.Future,akka.stream.scaladsl.Source[akka.util.ByteString,Any]] do not conform to trait SttpBackend's type parameter bounds [R[_],-S]
    implicit val backend = AkkaHttpBackend()

**Comment by adamw** [comment]
Which Scala, sttp, akka versions? Are you building through sbt? Did you try a clean rebuild?

**Comment by jiangnight** [comment]
Oh! I forget add akka-stream to my project , and when i add it, problem has solved! thanks a lot !
