### ISSUE TITLE
build definition doesn't load if sbt version is bumped 1.2.0 -> 1.2.1

### ISSUE THREAD

**Issue by SethTisue** [softwaremill/sttp#140]
seen in the Scala 2.12 community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3274/consoleFull

not sure if this is something weird in this repo, or something weird in sbt 1.2.1 itself. /cc @eed3si9n

```
[info] Loading settings for project sttp-build from plugins.sbt ...
[info] Loading project definition from /Users/tisue/sttp/project
[info] Updating ProjectRef(uri("file:/Users/tisue/sttp/project/"), "sttp-build")...
[warn] circular dependency found: org.seleniumhq.selenium#selenium-java;3.4.0->com.codeborne#phantomjsdriver;1.4.0->org.seleniumhq.selenium#selenium-java;3.1.0
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /Users/tisue/sttp/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] STTP_NATIVE *not* defined, *not* including sttp-native in the aggregate projects
[error] java.lang.ClassCastException: sbt.internal.util.Init$SettingList cannot be cast to sbt.internal.util.Init$Setting
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.Project$.transform(Project.scala:585)
[error] 	at sbt.ProjectExtra.inScope(Project.scala:905)
[error] 	at sbt.ProjectExtra.inScope$(Project.scala:904)
[error] 	at sbt.package$.inScope(package.scala:10)
[error] 	at wartremover.package$.wartremoverSettings$lzycompute(package.scala:17)
[error] 	at wartremover.package$.wartremoverSettings(package.scala:13)
[error] 	at wartremover.WartRemover$.projectSettings$lzycompute(WartRemover.scala:24)
[error] 	at wartremover.WartRemover$.projectSettings(WartRemover.scala:24)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1062)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1062)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1081)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1084)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1083)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1097)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.resolveProject(Load.scala:1051)
[error] 	at sbt.internal.Load$.finalizeProject$1(Load.scala:886)
[error] 	at sbt.internal.Load$.$anonfun$loadTransitive$10(Load.scala:944)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:944)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ClassCastException: sbt.internal.util.Init$SettingList cannot be cast to sbt.internal.util.Init$Setting
[error] Use 'last' for the full log.
```

**Comment by eed3si9n** [comment]
Right, so sbt 1.2.0 is a cursed version that will break the build (for anything except for sbt 1.2.0) if used to create a plugin - https://developer.lightbend.com/blog/2018-08-07-sbt-1-2-1/
Please republish sbt-softwaremill using sbt 1.2.1. Sorry that we couldn't catch this during RCs.

**Comment by adamw** [comment]
Fixed. Thanks @SethTisue @eed3si9n for the report and how to fix :)
