### ISSUE TITLE
HttpClientBackend throws `ClassCastException` on shutdown after update from 3.8.5 to 3.8.6

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/sttp#1686]
The following exception is being thrown after update from `3.8.5` to `3.8.6` (both using newest CE `3.4.4`):
```
java.lang.ClassCastException: class cats.effect.unsafe.WorkStealingThreadPool cannot be cast to class java.util.concurrent.ThreadPoolExecutor (cats.effect.unsafe.WorkStealingThreadPool is in unnamed module of loader 'app'; java.util.concurrent.ThreadPoolExecutor is in module java.base of loader 'bootstrap')
	at sttp.client3.HttpClientBackend$$anon$1.apply(HttpClientBackend.scala:108)
	at sttp.client3.HttpClientBackend$$anon$1.apply(HttpClientBackend.scala:107)
	at java.base/java.util.Optional.map(Optional.java:260)
	at sttp.client3.HttpClientBackend.$anonfun$close$1(HttpClientBackend.scala:107)
	at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
	at main$ @ com.superfund.exchange.webapi.user.WebApiUserNode$.main(WebApiUserNode.scala:8)
```
Diff between the versions: https://github.com/softwaremill/sttp/compare/v3.8.5...v3.8.6

**Comment by adamw** [comment]
Thanks for reporting :)
