### ISSUE TITLE
java.lang.NullPointerException: flowPublisher in HttpClientZioBackend when using httpClient with proxy

### ISSUE THREAD

**Issue by aleksandr-vin** [softwaremill/sttp#1697]
The stack trace:
```
[info] java.lang.NullPointerException: flowPublisher
[info] 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
[info] 	at org.reactivestreams.FlowAdapters.toPublisher(FlowAdapters.java:28)
[info] 	at sttp.client3.httpclient.zio.HttpClientZioBackend.publisherToBody(HttpClientZioBackend.scala:49)
[info] 	at sttp.client3.httpclient.zio.HttpClientZioBackend.publisherToBody(HttpClientZioBackend.scala:26)
[info] 	at sttp.client3.HttpClientAsyncBackend.$anonfun$sendRegular$3(HttpClientAsyncBackend.scala:51)
[info] 	at sttp.client3.HttpClientAsyncBackend.$anonfun$sendRegular$3$adapted(HttpClientAsyncBackend.scala:49)
[info] 	at sttp.client3.internal.SttpToJavaConverters$$anon$2.accept(SttpToJavaConverters.scala:12)
[info] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[info] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[info] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[info] 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[info] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
[info] 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

For:
```scala
val httpClient = HttpClient
      .newBuilder()
      .followRedirects(HttpClient.Redirect.NEVER)
      .connectTimeout(Duration.ofSeconds(timeout.toSeconds))
      .proxy(ProxySelector.of(new InetSocketAddress(proxyConfig.host, proxyConfig.port)))
      .build()

val backend = HttpClientZioBackend.usingClient(httpClient)
...
response <- backend.send(request.response(asJsonAlways[A]))
```

**Comment by aleksandr-vin** [comment]
After some investigation, that exception appears when proxy requests authentication (407 status code).

**Comment by VKFisher** [comment]
Any updates on this?

**Comment by UnknownNPC** [comment]
+1
Proxy auth doesn't work on sttp3  (3.8.16) & sttp4 (v4.0.0-M2). I seems somehow related to the next comment:
https://github.com/softwaremill/sttp/blob/fbc6f7e6ae222471fbae65c043bf6e15de74e84f/core/src/main/scalajvm/sttp/client4/httpclient/HttpClientBackend.scala#L128-L132

**Comment by arimu1** [comment]
Looks like this is the same root cause as #2050 and was fixed by:

- #2088 (v3) — `Option(response.body()).map(...).getOrElse(emptyBody())` so a null body from `HttpClient` (e.g. 407 / proxy auth failure) no longer reaches `FlowAdapters.toPublisher` / `HttpClientZioBackend`
- #2090 (v4 / master) — same null-safety path on `HttpClientAsyncBackend`, plus `ProxyAuthenticator` only answering `RequestorType.PROXY`, and proxy docs for `jdk.http.auth.tunneling.disabledSchemes`

Verified present on current `v3` and `master` tips. For Basic proxy auth through `HttpClient`, users still need to clear the JDK disabled schemes as documented in https://sttp.softwaremill.com/en/latest/conf/proxy.html (see also JDK-8229962).

This issue can probably be closed as fixed.

**Comment by adamw** [comment]
@arimu1 thanks for the nudge
