### ISSUE TITLE
Unable to open connection via a proxy

### ISSUE THREAD

**Issue by dkrawiec** [softwaremill/sttp#170]
Looks that change in commit faa97c618c9395335b91995c96792f8f3b61d300 introduced a bug which causes an exception when trying to establish a connection via a proxy.

`java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to java.net.HttpURLConnection
	at com.softwaremill.sttp.HttpURLConnectionBackend.openConnection(HttpURLConnectionBackend.scala:74)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:22)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:18)
	at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:17)
	at com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:12)
	at com.softwaremill.sttp.RequestT.send(RequestT.scala:229)`

**Comment by adamw** [comment]
That's how lack of tests + `asInstanceOf` ends ;)
I think 
https://github.com/softwaremill/sttp/commit/477a0278a78b76879bda5cbd4e25626b63dc20a2 should fix the problem - can you double-check?

And if you had an idea/some time to write an automated test for using a proxy - that would be great :)

**Comment by dkrawiec** [comment]
Sory for the delay. It was busy time before christmas. 

Your fix should work, but unfortunatelly I don't have an easy way to test authentication part.

Regarding the automation. Simplest would be to setup a wiremock server and some very simple http proxy server run from same jvm. I guess you could also set up wiremock so that it responds as if it was a proxy server.

**Comment by adamw** [comment]
@dkrawiec ok, thanks for the tips :) If you would ever have the time to implement this, it would be great :)
