### ISSUE TITLE
'java/net/http/HttpRequest' Error with simple example

### ISSUE THREAD

**Issue by gvlpedro** [softwaremill/sttp#1708]
I replicated this example from the documentation:
 https://sttp.softwaremill.com/en/latest/examples.html#post-a-form-using-the-synchronous-backend

But I get this error:

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: java/net/http/HttpRequest
	at sttp.client3.HttpClientSyncBackend$.apply$default$2(HttpClientSyncBackend.scala:86)
	at com.client.PostFormSynchronous2$.delayedEndpoint$com$client$PostFormSynchronous2$1(PostFormSynchronous2.scala:14)
	at com.client.PostFormSynchronous2$delayedInit$body.apply(PostFormSynchronous2.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.client.PostFormSynchronous2$.main(PostFormSynchronous2.scala:3)
	at com.client.PostFormSynchronous2.main(PostFormSynchronous2.scala)
Caused by: java.lang.NoClassDefFoundError: java/net/http/HttpRequest
	... 12 more
Caused by: java.lang.ClassNotFoundException: java.net.http.HttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

I created a simple code in github: 
    https://github.com/gvlpedro/testSttp3

I tried to include this  java.net.httpclient library but I thing there is an internal bug.

**Comment by adamw** [comment]
Which java version are you using?

**Comment by gvlpedro** [comment]
1.8

**Comment by adamw** [comment]
sttp requires at least java 11: https://sttp.softwaremill.com/en/latest/quickstart.html

If you require java 8, you can use versions before 3.6 (which started to require java 11: https://github.com/softwaremill/sttp/releases/tag/v3.6.1). However, the HttpClient backend isn't available there (as it ships in Java since 11), you'll have to use another one.
