### ISSUE TITLE
Null Pointer Exception on setting up proxy host & port in async-http-client implementation

### ISSUE THREAD

**Issue by singh05** [softwaremill/sttp#172]
PR from issue: https://github.com/softwaremill/sttp/pull/168 causes null pointer exception in while configuring proxy host and port via backend options. 

The exception is thrown from the setRealm method from async-http-client implementation (here: https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/proxy/ProxyServer.java#L134). 

The issue is caused from the bug at this line: https://github.com/softwaremill/sttp/pull/168/files#diff-24b84c96a3873a58f4257b3d34043703R311 (line 311) where it calls setRealm with orNull if no proxy authentication is used. 

Exception stack trace: 

`java.lang.NullPointerException
	at org.asynchttpclient.proxy.ProxyServer$Builder.setRealm(ProxyServer.java:139)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$.defaultClient(AsyncHttpClientBackend.scala:311)
	at com.softwaremill.sttp.asynchttpclient.future.AsyncHttpClientFutureBackend$.apply(AsyncHttpClientFutureBackend.scala:40)
	at com.agoda.content.commons.clients.http.HttpClient.liftedTree1$1(HttpClient.scala:40)
	at com.agoda.content.commons.clients.http.HttpClient.<init>(HttpClient.scala:39)
	at com.agoda.content.commons.clients.http.HttpClientTest.$anonfun$new$1(HttpClientTest.scala:31)
`

**Comment by adamw** [comment]
So the solution would be to call `setRealm` only if the value is defined?

**Comment by singh05** [comment]
Yes, I can make the PR in next 24 hours to help resolve it.

-- 
Prashant Singh

**Comment by adamw** [comment]
great, thanks! :)

**Comment by wwbakker** [comment]
In the mean time, as a workaround you can use version 1.5.0.

**Comment by adamw** [comment]
Fixed in 1.5.4
