### ISSUE TITLE
Unable to use sttp with scala-native

### ISSUE THREAD

**Issue by alexdupre** [softwaremill/sttp#188]
I don't know what I'm doing wrong, I cannot find a reason for the following behavior.

I compiled sttp-core with scala-native and I'm able to run `coreNative/test` without issues.

But if I try to build any main app, like:

```
import com.softwaremill.sttp._

object Main extends App {

  implicit val sttpBackend = CurlBackend()

  println(sttp.get(uri"localhost:51823/echo?a=b").send().unsafeBody)

}
```

I get the following error:

```[info] Running Main
[error] (run-main-b) scala.scalanative.runtime.UndefinedBehaviorError
[error] scala.scalanative.runtime.UndefinedBehaviorError
[error]         at scala.scalanative.runtime.package$.undefined(package.scala:34)
[error]         at scala.scalanative.native.package$.extern(package.scala:112)
[error]         at com.softwaremill.sttp.curl.CCurl$.init(CCurl.scala:17)
[error]         at com.softwaremill.sttp.curl.CurlApi$.init(CurlApi.scala:19)
[error]         at com.softwaremill.sttp.AbstractCurlBackend$$anonfun$send$1.apply(AbstractCurlBackend.scala:29)
[error]         at com.softwaremill.sttp.AbstractCurlBackend$$anonfun$send$1.apply(AbstractCurlBackend.scala:28)
[error]         at scala.scalanative.native.Zone$.apply(Zone.scala:21)
[error]         at com.softwaremill.sttp.AbstractCurlBackend.send(AbstractCurlBackend.scala:28)
[error]         at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:17)
[error]         at com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:12)
[error]         at com.softwaremill.sttp.RequestT.send(RequestT.scala:244)
[error]         at Main$.delayedEndpoint$Main$1(Main.scala:7)
[error]         at Main$delayedInit$body.apply(Main.scala:3)
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error]         at scala.App$class.main(App.scala:76)
[error]         at Main$.main(Main.scala:3)
[error]         at Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
```

The equivalent test class works like a charm:
```
import com.softwaremill.sttp._
import org.scalatest._

class Test extends FreeSpec with Matchers {

  implicit val backend = CurlBackend()

  "works" in {
    sttp.get(uri"localhost:51823/echo?a=b").send().unsafeBody should be("GET /echo a=b")
  }

}
```

**Comment by alexdupre** [comment]
It looks like a scala-native issue (?) that doesn't call the compiler on `runMain`, but just on `run`. Many hours wasted for a stupid thing.
