### ISSUE TITLE
Runtime crash for Scala 2.11 using AkkaHttpBackend

### ISSUE THREAD

**Issue by eliasapascaritei** [softwaremill/sttp#197]
Caused by: java.lang.ClassCastException: com.softwaremill.sttp.ResponseMetadata$$anon$1 cannot be cast to java.lang.Integer 	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101) 	at com.softwaremill.sttp.SttpApi$$anonfun$1.apply(SttpApi.scala:28) 	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend.com$softwaremill$sttp$asynchttpclient$AsyncHttpClientBackend$$readEagerResponse(AsyncHttpClientBackend.scala:234) 	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anon$1.onCompleted(AsyncHttpClientBackend.scala:72) 	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anon$1.onCompleted(AsyncHttpClientBackend.scala:70) 	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:66) 	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222) 	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257) 	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241) 	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:113) 	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142) 	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.lang.Thread.run(Thread.java:748)

**Comment by adamw** [comment]
Could you provide some code to reporduce the problem?

**Comment by eliasapascaritei** [comment]
implicit val sttpBackend: SttpBackend[Future, Source[ByteString, Any]] = AkkaHttpBackend()
def get(url: Uri,
                     headers: Seq[(String, String)],
                     cookies: Seq[(String, String)],
                     timeout: Duration): Future[HttpResponse] =
      sttp.get(uri"${url.toString}")
        .headers(headers.toMap)
        .cookies(cookies: _*)
        .readTimeout(timeout)
        .response(asByteArray)
        .send()
        .map(HttpResponse(_))

HttpResponse is a custom case class.

**Comment by adamw** [comment]
Hm you are using the `AkkaHttpBackend` or the `AsyncHttpClientBackend`? as the stack trace mentions `AsyncHttpClientBackend`.

Also, which version of sttp are you using?

**Comment by eliasapascaritei** [comment]
I was experiencing same issue with both akkaHttpBackend and AsyncFututreHttpBackend. It looks like the issue was that on other library I was overwriting the core dependency(as 1.5.9).
