### ISSUE TITLE
Timeout when using MonixAsyncHttpClientHandler 

### ISSUE THREAD

**Issue by omainegra** [softwaremill/sttp#2]
The following snippet throws `TimeoutException`

```scala
val sort: Option[String] = None
val query = "http language:scala"
val request = sttp.get(uri"https://api.github.com/search/repositories?q=$query&sort=$sort")

implicit val handler = MonixAsyncHttpClientHandler()
val response =
  Observable.fromTask {
    request.response(asStream[Observable[ByteBuffer]]).send()
  }
  .flatMap(_.body)
  .map(StandardCharsets.UTF_8.decode)
  .consumeWith(Consumer foreach print)
Await.result(response.runAsync(Scheduler.Implicits.global), Duration.Inf)
```
Stacktrace
```scala
Exception in thread "main" java.util.concurrent.TimeoutException: Request timeout to api.github.com/192.30.253.117:443 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)
```

But this one works perfectly

```scala
val response =
  Observable.fromTask {
    request.send()
  }
  .flatMap(str => Observable.apply(str.body))
  .consumeWith(Consumer foreach print)
Await.result(response.runAsync(Scheduler.Implicits.global), Duration.Inf)
```

The only difference is the body streaming. I can't think in a cause for the **timeout**

**Comment by adamw** [comment]
This only seems to happen with `https`. If you try getting e.g. `http://httpbin.org/get`, it works. But even without trying to consume the resulting stream when getting a secure site, it hangs. No idea why, though :)

That's my smaller test case:

```
    import monix.execution.Scheduler.Implicits.global
    implicit val h = MonixAsyncHttpClientHandler()

    try {
      val req = sttp.get(uri"https://softwaremill.com")

      val resp = Await.result(
        req.response(asStream[Observable[ByteBuffer]]).send().runAsync,
        1.minute)
      println(resp.body)
    } finally h.close()
```

Must be something in async-http-client, as the request is always created the same, it's the response handler that's changed.

**Comment by adamw** [comment]
Ok, I think I have a lead ... it seems sometimes only the `onStream` of `StremedAsyncHandler` is called in async-http-client, without `onComplete`.

**Comment by omainegra** [comment]
Indeed. I published your changes locally and my example worked as expected.

**Comment by adamw** [comment]
Ah I didn't see your comment. Great, and thanks a lot for testing & reporting problems!
