### ISSUE TITLE
Application startup fails after update of sttp.client3 to version 3.10.0 using with zio backend (Defect in zio.ZEnvironment)

### ISSUE THREAD

**Issue by seakayone** [softwaremill/sttp#2317]
We updated from
`"com.softwaremill.sttp.client3" %% "zio" % "3.9.8"`
to
`"com.softwaremill.sttp.client3" %% "zio" % "3.10.0"`.

When starting up the application it fails with the following stacktrace:

```
[info] 2024-10-18T15:44:51.311997+02:00 ERROR  zio-logger annotations=[] spans=[] cause=Exception in thread "zio-fiber-583583722,1629769644,142791163,41053299,333530872,1369000090,1098845082,1277197784,1819909806,915559965,1416679782,1621261600,779974035,1822713593,1883321198,1052708693" java.lang.Error: Defect in zio.ZEnvironment: HashSet(SttpBackend[=λ %0 → ZIO[-Any,+Throwable,+0],+{package::WebSockets & ZioStreams}]) statically known to be contained within the environment are missing
[info]  at zio.ZEnvironment.prune(ZEnvironment.scala:175)
[info]  at zio.ZEnvironment.union(ZEnvironment.scala:207)
[info]  at zio.ZLayer$ZLayerProvideSomeOps$.$greater$greater$greater$extension$$anonfun$1$$anonfun$1(ZLayer.scala:2066)
[info]  at zio.ZIO.zipWith$$anonfun$1$$anonfun$1(ZIO.scala:2574)
[info]  at zio.ZIO.map$$anonfun$1$$anonfun$1(ZIO.scala:972)
[info]  at swiss.dasch.Main.run(Main.scala:23)
[info] Exception in thread "zio-fiber-915559965,1629769644,969851240,958483221,1883321198" java.lang.InterruptedException: Interrupted by thread "zio-fiber-958483221"
[info]  at swiss.dasch.Main.run(Main.scala:23)
```

This is the only change in our application and [after reverting it the error is gone](https://github.com/dasch-swiss/dsp-ingest/pull/280/files)

We are using the `sttp: SttpBackend[Task, ZioStreams]` and construct it in a zio layer 

```
HttpClientZioBackend.layer(SttpBackendOptions.connectionTimeout(5.seconds)).orDie >+>
      ZLayer.derive[FetchAssetPermissionsLive]
```

**Comment by seakayone** [comment]
That solves our problem. Thanks.
