### ISSUE TITLE
java.net.ProtocolException: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by K68** [softwaremill/sttp#316]
When I use like this:
val httpMethod = "PATCH"
sttp.method(Method(httpMethod), uri"$url")

cause
```
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:440)
	at sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:519)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:28)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:19)
	at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:17)
	at com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:12)
	at com.softwaremill.sttp.RequestT.send(RequestT.scala:246)
	at controllers.AuthController.$anonfun$superRest$3(AuthController.scala:41)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
```

**Comment by K68** [comment]
Hello, I love sttp and used a lot in our projects. How to resolve the issues above? Pls help me

**Comment by adamw** [comment]
I'm afraid that's a limitation of Java's `HttpURLConnection`, so something outside of our control. A solution is to use another backend, for example OkHttp has a synchronous backend: https://sttp.readthedocs.io/en/latest/backends/okhttp.html
which should work fine w/ `PATCH`

**Comment by K68** [comment]
> I'm afraid that's a limitation of Java's `HttpURLConnection`, so something outside of our control. A solution is to use another backend, for example OkHttp has a synchronous backend: https://sttp.readthedocs.io/en/latest/backends/okhttp.html
> which should work fine w/ `PATCH`

Great, It works!! Thank you very much :)
