### ISSUE TITLE
Allow to configure Max redirects?

### ISSUE THREAD

**Issue by eschizoid** [softwaremill/sttp#522]
I couldn't find a way to configure the max redirects in order to get rid of this Exception

```
sttp.client.TooManyRedirectsException
	at sttp.client.FollowRedirectsBackend.$anonfun$followRedirect$2(FollowRedirectsBackend.scala:46)
	at scala.Option.fold(Option.scala:263)
	at sttp.client.FollowRedirectsBackend.followRedirect(FollowRedirectsBackend.scala:44)
	at sttp.client.FollowRedirectsBackend.$anonfun$sendWithCounter$1(FollowRedirectsBackend.scala:33)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Any help would be great, thanks!

**Comment by adamw** [comment]
You can do it using `basicRequest.maxRedirects(128)`.
