### ISSUE TITLE
Wrapping a get call in a Future with HttpClient Backend

### ISSUE THREAD

**Issue by Ha5hBr0wn** [softwaremill/sttp#525]
When I use the HttpClient backend

`implicit val sttpBackend = HttpClientSyncBackend()`

whenever I try to make a get call but wrap the result in a Future it never returns. I know this is a synchronous backend, but I was hoping I could wrap the call in a Future to make it asynchronous. It works fine when I don't wrap the call in a Future.

```
def get(key: String, secret: String, endpoint: String): Future[Account] = {
    val request = basicRequest.headers(Map(AlpacaInfo.key_header -> key, AlpacaInfo.secret_header -> secret)).
      get(uri"$endpoint/v2/account")

    val account_future = Future {request.send()}.map { (response) =>
      println("Yay")
      response.body match {
        case Right(contents) =>
          decode[Account](contents) match {
            case Right(account) => account
            case Left(ex) => throw ex
          }
        case Left(error) => throw new Exception(error + s" HTTP STATUS: ${response.code}")
      }
    }

    account_future
  }

```

The program calls this function and finishes and never prints out "Yay" when I use the HttpClientSync Backend. Also on sbt the first time I run it I get an 

`java.util.concurrent.ExecutionException: Boxed Exception`

But on subsequent runs I get the behavior where nothing is printed out. 

Also, when I try the OkHttpSync backend and wrap my calls in a future, and run the code using sbt, on the first run I always get

`sttp.client.SttpClientException$ReadException: java.io.InterruptedIOException: interrupted`

but on subsequent runs it is fine. ("Yay" gets printed only on subsequent runs as well) Every time I restart sbt I get the same behavior, and this behavior does not arise if I don't wrap things in Futures. Very Strange. 

Wrapping in a Future works for me when I use the default HttpURLConnectionBackend(), but I want to incorporate Websockets at some point so I thought I'd try the other backends that have WebSocket support. I'm trying to avoid the asynchronous frameworks that I don't understand and. just manage parallelism myself with Futures and Promises.  

Note: I change nothing besides the implicit backend value in my code and it works for HttpURLConnectionBackend but not HttpClientSyncBackend. If I just remove the Future wrapping it works for HttpClientSyncBackend and OkHttpSyncBackend as expected.

If I try using the Future based versions of these backends neither prints out an error on the first run, and just behave as the subsequent runs of the non Futures version. So HttpClient still doesn't print anything and OkHttp works normally (Although all this other behavior I described is worrisome). 

I'd prefer to use the Sync versions so that I can handle all the parallelism myself.

Is there any way to fix this? Thanks for any help!

**Comment by adamw** [comment]
Can you post the entire code fragment with which you construct the backend? Or even better, code which would reproduce the problem :)

**Comment by Ha5hBr0wn** [comment]
So I am interacting with the Alpaca API (trading brokerage) and I am using sttp to make requests and circe to extract the requests into a case class. I also using json4s for converting a Map to a json string since it can handle Map(String, _) and circe can't. 

Now for the actual code...

In one file to wrap the Accounts API

```
import sttp.client._

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

import io.circe.generic.auto._
import io.circe.parser.decode



/** Represents an Account as returned by the API */
case class Account(id: String, account_number: String, status: String, currency: String,
                   buying_power: String, regt_buying_power: String, daytrading_buying_power: String, cash: String,
                   portfolio_value: String, pattern_day_trader: Boolean, trading_blocked: Boolean,
                   transfers_blocked: Boolean, account_blocked: Boolean, created_at: String,
                   trade_suspended_by_user: Boolean, multiplier: String, shorting_enabled: Boolean,
                   equity: String, last_equity: String, long_market_value: String, short_market_value: String,
                   initial_margin: String, maintenance_margin: String, last_maintenance_margin: String,
                   sma: String, daytrade_count: Int
                   )

/** Provides a method for getting your account*/
case object Account {
  implicit val backend = Extras.sttp_backend

  /** Returns a successfully parsed Account instance, or throws an error. Errors can be caused by parsing, HTTP error
   * status codes, and java exceptions due to failures to connect such as no internet or connection timeout.
   * Note the call returns a Future*/
  def get(key: String, secret: String, endpoint: String): Future[Account] = {
    val request = basicRequest.headers(Map(AlpacaInfo.key_header -> key, AlpacaInfo.secret_header -> secret)).
      get(uri"$endpoint/v2/account")

    val result_future = Future {request.send()}.map { (response) =>
      response.body match {
        case Right(body) =>
          decode[Account](body) match {
            case Right(result) => result
            case Left(ex) => throw ex
          }
        case Left(error) => throw new Exception(error + s" HTTP STATUS: ${response.code}")
      }
    }
    result_future
  }


}
```

And in another file that I use for testing some stuff out and keeping my implicits 

```
import org.json4s._

import sttp.client.okhttp.OkHttpSyncBackend

import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.{Failure, Success}

import io.circe.generic.auto._
import io.circe.syntax._


object Extras{
  implicit val sttp_backend = OkHttpSyncBackend() //For sttp
  implicit val formats = DefaultFormats //For json4s
}


object Playground extends App{

  def makeOrderTest: Unit = {
    val order_future = Order.makeOrder(AlpacaInfo.paper_key, AlpacaInfo.paper_secret, AlpacaInfo.paper_endpoint,
      Map("symbol"->"FB", "qty"->"1", "side"->"buy", "type"->"market", "time_in_force"->"day"))
    order_future onComplete {
      case Success(order) => println(order.asJson)
      case Failure(ex) => println(ex.toString)
    }
  }

  def replaceOrderTest: Unit = {
    val order_future = Order.replaceOrder(AlpacaInfo.paper_key, AlpacaInfo.paper_secret, AlpacaInfo.paper_endpoint,
      "anOrderIDIRemovedForSecurity", Map("qty"->"50"))
    order_future onComplete {
      case Success(order) => println(order.asJson)
      case Failure(ex) => println(ex.toString)
    }
  }

  def getOrdersTest: Unit = {
    val orders_future = Order.get(AlpacaInfo.paper_key, AlpacaInfo.paper_secret, AlpacaInfo.paper_endpoint)
    orders_future onComplete {
      case Success(orders) => orders foreach {order => println(order.asJson)}
      case Failure(ex) => println(ex.toString)
    }
  }

  def getOrderTest: Unit = {
    val order_future = Order.getOrder(AlpacaInfo.paper_key, AlpacaInfo.paper_secret, AlpacaInfo.paper_endpoint,
      "anorderIDIRemovedForSecurity")
    order_future onComplete {
      case Success(order) => println(order.asJson)
      case Failure(ex) => println(ex.toString)
    }
  }

  def getAccountTest: Unit = {
    val account_future = Account.get(AlpacaInfo.paper_key, AlpacaInfo.paper_secret, AlpacaInfo.paper_endpoint)
    account_future onComplete {
      case Success(account) => println(account.asJson)
      case Failure(ex) => println(ex.toString)
    }
  }

  getAccountTest

}
```
AlpacaInfo is just an object I use to store my API keys and the base endpoint for my paper (fake trading) and live account. As it is now with the OkHttpSync backend the first time I run it in sbt from the terminal I get the exception I mentioned above and from there it works as intended if I just run it again. Switching it to HttpClientSync backend will produce that other exception I mentioned above on the first run and on subsequent runs will just fail to do anything. The program finished but it seems the http request never returns. Using the HttpClientFuture backend (after adjusting the code in Account by removing the Future wrapping on the send call itself) no error is thrown on the first run but still the send call seems to never return. OkHttpFuture works fine, but this other behavior leaves me wary of when it might fail. 

Also as a separate question if I am using the Sync backend is there any need to close() the backend. And in the case of using the Future backends if there are still Futures being evaluated that involve making http requests when the close() runs what would be the expected behavior? Should I only call close() after I am sure all the asynchronous computation is complete or can I just call it after I have set the asynchronous computations in motion?

Thanks for the help! I really like the library btw, it's really flexible and will fit my needs perfectly as soon as I can fix this darn bug.

**Comment by adamw** [comment]
So you're getting the exception both when using `HttpClientSyncBackend` and `OkHttpSyncBackend`? Can you share some part of the stack trace (removing your classes, of course)? At which invocation does the exception happen?

As for your question about closing, this depends on the backend, not on sync vs async. E.g. with `OkHttpSyncBackend`, you should close it - there's a thread pool that is being started when the backend is allocated, and these threads needs to be closed. Similar for `HttpClientSyncBackend`.

**Comment by Ha5hBr0wn** [comment]
So with OkHttpSyncBackend on the first run I get
```
sttp.client.SttpClientException$ReadException: java.io.InterruptedIOException: interrupted
        at sttp.client.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:41)
        at sttp.client.okhttp.OkHttpBackend$.exceptionToSttpClientException(OkHttpBackend.scala:197)
        at sttp.client.okhttp.OkHttpSyncBackend.$anonfun$adjustExceptions$1(OkHttpBackend.scala:241)
        at sttp.client.SttpClientException$.adjustSynchronousExceptions(SttpClientException.scala:50)
        at sttp.client.okhttp.OkHttpSyncBackend.adjustExceptions(OkHttpBackend.scala:241)
        at sttp.client.okhttp.OkHttpSyncBackend.send(OkHttpBackend.scala:203)
        at sttp.client.okhttp.OkHttpSyncBackend.send(OkHttpBackend.scala:201)
        at sttp.client.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)
        at sttp.client.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:17)
        at sttp.client.RequestT.send(RequestT.scala:279)
        at alpaca.Account$.$anonfun$get$1(Account.scala:35)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
        at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
        at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.io.InterruptedIOException: interrupted
        at okio.Timeout.throwIfReached(Timeout.kt:98)
        at okio.OutputStreamSink.write(JvmOkio.kt:50)
        at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
        at okio.RealBufferedSink.flush(RealBufferedSink.kt:247)
        at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.kt:155)
        at okhttp3.internal.connection.Exchange.finishRequest(Exchange.kt:91)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at sttp.client.okhttp.OkHttpSyncBackend.$anonfun$send$1(OkHttpBackend.scala:207)
        at sttp.client.SttpClientException$.adjustSynchronousExceptions(SttpClientException.scala:48)
        ... 20 more
```

On subsequent runs it works fine. With HttpClient on the first run I get 
```
java.util.concurrent.ExecutionException: Boxed Exception
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
        at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:407)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:469)
        at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
        at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
        at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:541)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at sttp.client.httpclient.HttpClientSyncBackend.$anonfun$send$1(HttpClientSyncBackend.scala:28)
        at sttp.client.SttpClientException$.adjustSynchronousExceptions(SttpClientException.scala:48)
        at sttp.client.httpclient.HttpClientSyncBackend.adjustExceptions(HttpClientSyncBackend.scala:56)
        at sttp.client.httpclient.HttpClientSyncBackend.send(HttpClientSyncBackend.scala:26)
        at sttp.client.httpclient.HttpClientSyncBackend.send(HttpClientSyncBackend.scala:21)
        at sttp.client.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)
        at sttp.client.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:17)
        at sttp.client.RequestT.send(RequestT.scala:279)
        at alpaca.Account$.$anonfun$get$1(Account.scala:35)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        ... 11 more
()
```

On subsequent runs there is no stack trace as there is no exception, but the get call never completes. When I say first run I mean the first time I enter "run" in a particular sbt session. So if I use HttpSyncBackend and run it I'll get an error, and then if I change the code to use OkHttpSync backend while keeping the sbt session open and then run it will work. 

Also follow up on my last question when should close() be called on the backend. Can it be called after all the async processing is up and running (Futures are set but not completed), but not complete or do I have to wait for all the Futures I sent out to be completed before calling close to avoid shutting down before a Future actually makes the get call?

**Comment by adamw** [comment]
Sorry, but I can't reproduce the problem. In both cases it seems that "something" is interrupting the thread on which you are running the requests, hence the `java.lang.InterruptedException` (which is the root cause of both exceptions). This seems unrelated to sttp, but probably something else in your system. 

I don't think I'll be able to say anything more without a runnable, reproducible example. You should probably check if you have any interrupts in your application.

As for closing, both in case of the OkHttp client and the built-in HttpClient any submitted tasks (requests) are completed) before the pool is shut down. However, the call won't wait for running requests tasks to be completed (it will complete right away).

**Comment by Ha5hBr0wn** [comment]
Ok thanks anyways. I think I might actually use the Akka backend as I will use actors for concurrency. Passing in an Akka Typed system will work right?

Also do I need to terminate the system and close the backend or is terminating the system at the end of the application sufficient.

**Comment by adamw** [comment]
@Ha5hBr0wn yes, a typed actor system has an untyped one underneath, this will work :)

Terminating the system is sufficient, it will also close any of the http-related actors

**Comment by Ha5hBr0wn** [comment]
I switched over to using the Akka Backend and everything is going well. Interestingly when I reimplemented using Actors as my unit for concurrency rather than futures the other backends also start working. 

Is all the streaming handled in the background. I learned how to use the Actor framework but am still not entirely familiar with streams and couldn't understand how Akka-http works (yet). If I don't do streaming requests and responses is the backend dealing with the streams part of Akka-http and just giving me back the entire thing?

When I do learn streams would requesting the body as a stream for example just take that load off the backend and let me deal with the stream myself?

Sorry for spamming you with questions, this is one of my first big personal projects and I have a lot to learn.

**Comment by adamw** [comment]
Yes, streaming is handled in a non-blocking way in the background. If you don't use streaming request/response bodies in sttp, the stream will be converted to the desired type (e.g. `String` or `Array[Byte]`) for you - also in a non-blocking way. This is done by consuming the stream, accumulating all the data and then converting to the desired types. No actors are started by sttp - however, sttp operates on `Future`s, which are run on the actor thread pool. E.g. consuming a stream gives you a `Future`, and then converting that to another type is again done as mapping a `Future`.

**Comment by Ha5hBr0wn** [comment]
Thank you!
