### ISSUE TITLE
Armeria-fs2 large stream test failing

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#873]
On CI, I often get:

```
[info] ArmeriaFs2StreamingTest:
[info] - stream request body
[info] - stream large request body
[info] - handle server sent events SSE
[info] - receive a stream
[info] - receive a stream and ignore it (without consuming)
[info] - receive a stream (unsafe)
[info] - receive a large stream (unsafe) *** FAILED ***
[info]   com.linecorp.armeria.client.ResponseTimeoutException:
[info]   at com.linecorp.armeria.client.ResponseTimeoutException.get(ResponseTimeoutException.java:36)
[info]   at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.initTimeout(HttpResponseDecoder.java:387)
[info]   at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:120)
[info]   at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:54)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[info]   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[info]   at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[info]   at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
```

**Comment by adamw** [comment]
Maybe @ikhoon or @ngbinh would have an idea. I'll disable that test for now.

**Comment by ikhoon** [comment]
Hmm... Let me check it.
