### ISSUE TITLE
[HttpClientZioBackend] WebSocket send methods are not thread-safe

### ISSUE THREAD

**Issue by yangzai** [softwaremill/sttp#902]
Sample code:

```scala
import sttp.client3._
//import sttp.client3.asynchttpclient.zio.{AsyncHttpClientZioBackend, sendR}
import sttp.client3.httpclient.zio.{HttpClientZioBackend, sendR}
import zio._
import zio.console.Console.Service.live.putStrLn


object ParallelUnsafe extends zio.App {
  val wsReq = basicRequest.get(uri"wss://echo.websocket.org") response asWebSocketAlways[Task, Unit] { ws =>
    ZIO.foreachPar_(1 to 10) { _ =>
      ws.sendText("0123456789") &> //not thread-safe
        ws.receiveText().flatMap(s => putStrLn(s"msg: $s"))
    }
  }
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    sendR(wsReq).provideCustomLayer(HttpClientZioBackend.layer()).exitCode
}

object ParallelSafe extends zio.App {
  val wsReq = basicRequest.get(uri"wss://echo.websocket.org") response asWebSocketAlways[Task, Unit] { ws =>
    for {
      //workaround for thread-safe parallel send:
      // buffer queue with a dedicated fiber just for sending
      sendQ <- Queue.unbounded[String]
      fiber <- sendQ.take.flatMap(ws.sendText).forever.fork

      _ <- ZIO.foreachPar_(1 to 10) { _ =>
        //IIRC receive does have similar issues as well but I can't seem to reproduce it here
        sendQ.offer("0123456789") &>
          ws.receiveText().flatMap(s => putStrLn(s"msg: $s"))
      }

      _ <- fiber.interrupt
    } yield ()
  }
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    sendR(wsReq).provideCustomLayer(HttpClientZioBackend.layer()).exitCode
}
```

Error message for `ParallelUnsafe`:
```
Fiber failed.
A checked error was not handled.
java.lang.IllegalStateException: Send pending
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:182)
	at sttp.client3.httpclient.WebSocketImpl.$anonfun$send$1(WebSocketImpl.scala:45)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:361)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:769)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Only happens with `HttpClientZioBackend`. No issues with `AsyncHttpClientZioBackend`.

**Comment by adamw** [comment]
Thanks for the report! `send`s are fixed in 3.2.3. For `receive`s, I've added a note to the docs that they should be called from a single thread/fiber, or at least sequentially. Even though concurrent receives would work, you could get fragments of the same frame in different threads, which probably isn't what you'd want./
